In [1]:
%run main.ipynb

In [2]:
import psycopg2
import pgadmin_password
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [3]:
wine_quality_df = df
wine_quality_df.head()

,wine_type_id,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfure_dioxide,density,ph,sulphates,alcohol,quality
wine_id,,,,,,,,,,,,,
1,0,7.4,0.7,0.0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
2,0,7.8,0.88,0.0,2.6,0.098,25,67,0.9968,3.2,0.68,9.8,5
3,0,7.8,0.76,0.04,2.3,0.092,15,54,0.997,3.26,0.65,9.8,5
4,0,11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8,6
5,0,7.4,0.7,0.0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5

In [4]:
# Define the features set.
X = wine_quality_df.copy()
X = wine_quality_df.drop("quality", axis=1)
X.head()

,wine_type_id,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfure_dioxide,density,ph,sulphates,alcohol
wine_id,,,,,,,,,,,,
1,0,7.4,0.7,0.0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4
2,0,7.8,0.88,0.0,2.6,0.098,25,67,0.9968,3.2,0.68,9.8
3,0,7.8,0.76,0.04,2.3,0.092,15,54,0.997,3.26,0.65,9.8
4,0,11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8
5,0,7.4,0.7,0.0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4

In [14]:
# Define the target set.
y = wine_quality_df["quality"].ravel()
y[:5]

array([5, 5, 5, 6, 5], dtype=int64)

In [16]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [7]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [9]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [10]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [11]:
predictions

array([5, 6, 7, ..., 6, 5, 6], dtype=int64)

In [19]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 3", "Actual 4", "Actual 5", "Actual 6", "Actual 7", "Actual 8", "Actual 9"],
        columns=["Predicted 3", "Predicted 4", "Predicted 5", "Predicted 6", "Predicted 7", "Predicted 8", "Predicted 9"])

cm_df

,Predicted 3,Predicted 4,Predicted 5,Predicted 6,Predicted 7,Predicted 8,Predicted 9
Actual 3,0,0,7,3,0,0,0
Actual 4,0,7,27,15,0,0,0
Actual 5,0,2,387,149,3,0,0
Actual 6,0,1,108,532,60,0,0
Actual 7,0,0,5,116,143,1,0
Actual 8,0,0,0,16,19,23,0
Actual 9,0,0,0,0,1,0,0

In [20]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [21]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

,Predicted 3,Predicted 4,Predicted 5,Predicted 6,Predicted 7,Predicted 8,Predicted 9
Actual 3,0,0,7,3,0,0,0
Actual 4,0,7,27,15,0,0,0
Actual 5,0,2,387,149,3,0,0
Actual 6,0,1,108,532,60,0,0
Actual 7,0,0,5,116,143,1,0
Actual 8,0,0,0,16,19,23,0
Actual 9,0,0,0,0,1,0,0

Accuracy Score : 0.672
Classification Report
              precision    recall  f1-score   support

           3       0.00      0.00      0.00        10
           4       0.70      0.14      0.24        49
           5       0.72      0.72      0.72       541
           6       0.64      0.76      0.69       701
           7       0.63      0.54      0.58       265
           8       0.96      0.40      0.56        58
           9       0.00      0.00      0.00         1

    accuracy                           0.67      1625
   macro avg       0.52      0.36      0.40      1625
weighted avg       0.68      0.67      0.66      1625

C:\Users\Reid\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Reid\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Reid\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [22]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.00349016, 0.0736871 , 0.09939204, 0.07851982, 0.08699359,
       0.08474931, 0.08574692, 0.09149427, 0.10283995, 0.08316835,
       0.08611683, 0.12380165])

In [23]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.12380164880401537, 'alcohol'),
 (0.10283995256345943, 'density'),
 (0.09939204040264991, 'volatile_acidity'),
 (0.09149427300414172, 'total_sulfure_dioxide'),
 (0.0869935945447905, 'residual_sugar'),
 (0.08611682619230096, 'sulphates'),
 (0.0857469229005829, 'free_sulfur_dioxide'),
 (0.08474931171153995, 'chlorides'),
 (0.08316835394276152, 'ph'),
 (0.07851982451047448, 'citric_acid'),
 (0.07368709583075714, 'fixed_acidity'),
 (0.003490155592526056, 'wine_type_id')]